name: Update Committee Votes Gist

on:
  push:
    branches:
      - main # Or your default branch
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Specify a version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script to fetch votes and update Gist
        env:
          GIST_UPDATE_TOKEN: ${{ secrets.GIST_UPDATE_TOKEN }}
          COMMITTEE_GIST: ${{ secrets.COMMITTEE_GIST }} # Although the script uses the Gist ID directly now
        run: python committee_votes.py

